In [1]:
import skmob
import pandas as pd
import geopandas as gpd
from skmob.models.epr import Ditras
from skmob.models.markov_diary_generator import MarkovDiaryGenerator
from skmob.preprocessing import filtering, compression, detection, clustering

In [9]:
url = skmob.utils.constants.GEOLIFE_SAMPLE
df = pd.read_csv(url, sep=',', compression='gzip')
tdf = skmob.TrajDataFrame(df, latitude='lat', longitude='lon', user_id='user', datetime='datetime')
#ctdf = compression.compress(tdf)
stdf = detection.stay_locations(tdf)
cstdf = clustering.cluster(stdf)
mdg = MarkovDiaryGenerator()
mdg.fit(cstdf, 2, lid='cluster')

100%|█████████████████████████████████████████████| 2/2 [00:00<00:00,  5.74it/s]

In [29]:
start_time = pd.to_datetime('2022/04/20 08:00:00')
diary = mdg.generate(30*24, start_time)
print(diary)

              datetime  abstract_location
0  2022-04-20 08:00:00                  0
1  2022-04-20 12:00:00                  1
2  2022-04-20 21:00:00                  2
3  2022-04-21 08:00:00                  0
4  2022-04-21 17:00:00                  1
..                 ...                ...
93 2022-05-18 10:00:00                  1
94 2022-05-18 12:00:00                  2
95 2022-05-18 14:00:00                  0
96 2022-05-18 21:00:00                  1
97 2022-05-18 22:00:00                  0

[98 rows x 2 columns]

In [27]:
diary['abstract_location'].unique()

array([0, 1, 2, 3, 4, 5])

In [28]:
diary = mdg.generate(30*24, start_time)

In [21]:
print(diary)

              datetime  abstract_location
0  2022-04-20 08:00:00                  0
1  2022-04-20 21:00:00                  1
2  2022-04-20 22:00:00                  2
3  2022-04-20 23:00:00                  0
4  2022-04-21 12:00:00                  1
..                 ...                ...
66 2022-05-16 17:00:00                  3
67 2022-05-17 08:00:00                  0
68 2022-05-18 22:00:00                  1
69 2022-05-19 08:00:00                  0
70 2022-05-19 23:00:00                  1

[71 rows x 2 columns]

In [18]:
tdf['uid']

0         1
1         1
2         1
3         1
4         1
         ..
217648    5
217649    5
217650    5
217651    5
217652    5
Name: uid, Length: 217653, dtype: int64

In [10]:
df2 = pd.read_csv("2020_AR_Region_Mobility_Report.csv")

In [12]:
len(df2["place_id"].unique())

441

In [13]:
df.head()

         lat         lng             datetime  uid
0  39.984094  116.319236  2008-10-23 05:53:05    1
1  39.984198  116.319322  2008-10-23 05:53:06    1
2  39.984224  116.319402  2008-10-23 05:53:11    1
3  39.984211  116.319389  2008-10-23 05:53:16    1
4  39.984217  116.319422  2008-10-23 05:53:21    1

In [15]:
df2.shape

(130441, 15)

In [16]:
df.shape

(217653, 4)

In [18]:
df3 = df2[["place_id", "date"]]

In [20]:
df3.shape

(130441, 2)

In [22]:
df3['datetime'] = df3["date"]

/tmp/ipykernel_11648/1303044958.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['datetime'] = df3["date"]

In [23]:
df3.head()

                      place_id        date    datetime
0  ChIJZ8b99fXKvJURqA_wKpl3Lz0  2020-02-15  2020-02-15
1  ChIJZ8b99fXKvJURqA_wKpl3Lz0  2020-02-16  2020-02-16
2  ChIJZ8b99fXKvJURqA_wKpl3Lz0  2020-02-17  2020-02-17
3  ChIJZ8b99fXKvJURqA_wKpl3Lz0  2020-02-18  2020-02-18
4  ChIJZ8b99fXKvJURqA_wKpl3Lz0  2020-02-19  2020-02-19

In [27]:
cstdf["uid"].value_counts()

5    252
1    161
Name: uid, dtype: int64

In [28]:
skmob.utils.constants.GEOLIFE_SAMPLE

'https://raw.githubusercontent.com/scikit-mobility/scikit-mobility/master/examples/geolife_sample.txt.gz'

In [29]:
df

              lat         lng             datetime  uid
0       39.984094  116.319236  2008-10-23 05:53:05    1
1       39.984198  116.319322  2008-10-23 05:53:06    1
2       39.984224  116.319402  2008-10-23 05:53:11    1
3       39.984211  116.319389  2008-10-23 05:53:16    1
4       39.984217  116.319422  2008-10-23 05:53:21    1
...           ...         ...                  ...  ...
217648  39.999896  116.327290  2009-03-19 05:46:02    5
217649  39.999899  116.327352  2009-03-19 05:46:07    5
217650  39.999945  116.327394  2009-03-19 05:46:12    5
217651  40.000015  116.327433  2009-03-19 05:46:17    5
217652  39.999978  116.327460  2009-03-19 05:46:37    5

[217653 rows x 4 columns]

In [31]:
tdf = skmob.io.file.load_geolife_trajectories("Geolife Trajectories 1.3/")

  0%|                                                   | 0/182 [00:00<?, ?it/s]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
  1%|▏                                          | 1/182 [00:00<00:20,  8.65it/s]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
  1%|▍                                          | 2/182 [00:01<02:19,  1.29it/s]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
  2%|▋                                        | 3/182 [01:06<1:30:26, 30.31s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
  2%|▉                                          | 4/182 [01:11<59:47, 20.16s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
  3%|█▏                                         | 5/182 [01:11<38:19, 12.99s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
  3%|█▍                                         | 6/182 [01:11<25:25,  8.67s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
  4%|█▋                                         | 7/182 [01:13<18:28,  6.33s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
  4%|█▉                                         | 8/182 [01:15<14:10,  4.89s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
  5%|██▏                                        | 9/182 [01:16<10:59,  3.81s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
  5%|██▎                                       | 10/182 [01:18<09:06,  3.18s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
  6%|██▌                                       | 11/182 [01:26<13:00,  4.57s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
  7%|██▊                                       | 12/182 [01:55<34:09, 12.06s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
  7%|███                                       | 13/182 [01:55<23:45,  8.44s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
  8%|███▏                                      | 14/182 [02:10<29:21, 10.49s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
  9%|███▋                                      | 16/182 [02:13<17:16,  6.24s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
  9%|███▉                                      | 17/182 [02:14<13:24,  4.88s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
 10%|████▏                                     | 18/182 [02:14<09:57,  3.64s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
 11%|████▌                                     | 20/182 [02:25<12:13,  4.53s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
 12%|████▊                                     | 21/182 [02:27<10:35,  3.95s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
 12%|█████                                     | 22/182 [02:28<08:14,  3.09s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
 13%|█████▎                                    | 23/182 [02:28<06:12,  2.35s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
 13%|█████▌                                    | 24/182 [02:30<05:34,  2.12s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
 14%|█████▊                                    | 25/182 [02:44<14:27,  5.53s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
 14%|██████                                    | 26/182 [02:50<14:41,  5.65s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
 15%|██████▏                                   | 27/182 [02:52<11:41,  4.53s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
 15%|██████▍                                   | 28/182 [02:52<08:22,  3.26s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
 16%|██████▋                                   | 29/182 [02:53<06:51,  2.69s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
 16%|██████▉                                   | 30/182 [02:55<05:54,  2.33s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
 17%|███████▏                                  | 31/182 [02:55<04:48,  1.91s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
 18%|███████▌                                  | 33/182 [02:56<02:57,  1.19s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
 19%|████████                                  | 35/182 [02:57<02:06,  1.17it/s]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
 20%|████████▎                                 | 36/182 [03:09<08:09,  3.35s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
 20%|████████▌                                 | 37/182 [03:09<06:14,  2.58s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
 21%|████████▊                                 | 38/182 [03:09<04:46,  1.99s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
 21%|█████████                                 | 39/182 [03:11<04:16,  1.79s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
 22%|█████████▏                                | 40/182 [03:12<03:45,  1.59s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
 23%|█████████▋                                | 42/182 [03:15<03:50,  1.65s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
 24%|█████████▉                                | 43/182 [03:28<09:53,  4.27s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
 24%|██████████▏                               | 44/182 [03:28<07:36,  3.31s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
 25%|██████████▍                               | 45/182 [03:30<06:42,  2.93s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
 25%|██████████▌                               | 46/182 [03:38<09:34,  4.23s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
 26%|██████████▊                               | 47/182 [03:43<09:51,  4.38s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
 26%|███████████                               | 48/182 [03:43<07:06,  3.18s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
 27%|███████████▎                              | 49/182 [03:43<05:05,  2.30s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
 27%|███████████▌                              | 50/182 [03:50<07:51,  3.57s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
 28%|███████████▊                              | 51/182 [03:50<05:35,  2.56s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
 29%|████████████                              | 52/182 [03:58<09:16,  4.28s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
 30%|████████████▍                             | 54/182 [03:58<05:02,  2.36s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
 31%|████████████▉                             | 56/182 [04:19<11:46,  5.60s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
 32%|█████████████▍                            | 58/182 [05:01<22:45, 11.01s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
 32%|█████████████▌                            | 59/182 [05:03<18:52,  9.20s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
 33%|█████████████▊                            | 60/182 [05:04<14:54,  7.33s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
 34%|██████████████▎                           | 62/182 [05:04<08:56,  4.47s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
 35%|██████████████▌                           | 63/182 [05:04<06:58,  3.52s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)
 35%|██████████████▊                           | 64/182 [05:04<05:22,  2.73s/it]/home/olix/anaconda3/envs/ct/lib/python3.9/site-packages/skmob/io/file.py:133: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  tdf = tdf.append(tdf0)

In [36]:
len(tdf.uid.unique())

182

In [37]:
ctdf = compression.compress(tdf)

In [38]:
stdf = detection.stay_locations(ctdf)

In [39]:
cstdf = clustering.cluster(stdf)

In [40]:
mdg = MarkovDiaryGenerator()
mdg.fit(cstdf, 182, lid='cluster')

 99%|████████████████████████████████████████▊| 181/182 [01:06<00:00,  2.73it/s]

In [41]:
start_time = pd.to_datetime('2022/04/20 08:00:00')
diary = mdg.generate(30*24, start_time)
print(diary)

              datetime  abstract_location
0  2022-04-20 08:00:00                  0
1  2022-04-24 02:00:00                  1
2  2022-04-24 06:00:00                  0
3  2022-04-25 21:00:00                  1
4  2022-04-26 09:00:00                  2
5  2022-04-26 10:00:00                  3
6  2022-04-26 12:00:00                  4
7  2022-04-26 18:00:00                  0
8  2022-04-27 09:00:00                  1
9  2022-04-27 21:00:00                  2
10 2022-04-28 08:00:00                  0
11 2022-04-28 12:00:00                  1
12 2022-04-28 13:00:00                  2
13 2022-04-28 14:00:00                  3
14 2022-04-28 17:00:00                  4
15 2022-04-29 03:00:00                  5
16 2022-04-29 17:00:00                  6
17 2022-04-30 12:00:00                  7
18 2022-04-30 15:00:00                  8
19 2022-04-30 16:00:00                  0
20 2022-05-02 18:00:00                  1
21 2022-05-03 11:00:00                  2
22 2022-05-03 13:00:00                  3
23 2022-05-03 14:00:00                  4
24 2022-05-03 17:00:00                  5
25 2022-05-03 19:00:00                  6
26 2022-05-03 21:00:00                  0
27 2022-05-05 08:00:00                  1
28 2022-05-05 11:00:00                  2
29 2022-05-05 16:00:00                  0
30 2022-05-08 11:00:00                  1
31 2022-05-08 12:00:00                  2
32 2022-05-08 13:00:00                  0
33 2022-05-11 21:00:00                  1
34 2022-05-11 22:00:00                  2
35 2022-05-12 10:00:00                  0
36 2022-05-13 09:00:00                  1
37 2022-05-14 08:00:00                  2
38 2022-05-14 21:00:00                  3
39 2022-05-15 05:00:00                  4
40 2022-05-15 18:00:00                  5
41 2022-05-15 21:00:00                  6
42 2022-05-16 19:00:00                  7
43 2022-05-17 07:00:00                  8
44 2022-05-17 16:00:00                  9
45 2022-05-17 17:00:00                 10
46 2022-05-17 19:00:00                  0
47 2022-05-17 20:00:00                  1
48 2022-05-17 22:00:00                  2
49 2022-05-18 00:00:00                  3
50 2022-05-18 04:00:00                  4
51 2022-05-18 16:00:00                  5
52 2022-05-18 17:00:00                  0

In [44]:
diary["abstract_location"].unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
cstdf

,lat,lng,datetime,uid,leaving_datetime,cluster
0,39.983806,116.299436,2008-10-23 03:01:40,000,2008-10-23 04:08:07,122
1,39.999666,116.324510,2008-10-23 04:32:52,000,2008-10-23 09:42:25,0
2,40.008994,116.321445,2008-10-23 09:44:50,000,2008-10-23 10:09:16,1
3,40.007759,116.319107,2008-10-23 10:09:16,000,2008-10-23 10:31:25,1
4,40.008842,116.321856,2008-10-23 10:31:25,000,2008-10-26 13:44:07,1
...,...,...,...,...,...,...
35912,39.977017,116.310683,2008-02-17 01:25:55,181,2008-02-17 04:17:57,3
35913,39.983617,116.307908,2008-02-17 04:27:53,181,2008-02-17 05:21:46,8
35914,39.983600,116.300225,2008-02-17 05:25:01,181,2008-02-17 10:39:57,2
35915,39.989217,116.298675,2008-02-17 10:42:11,181,2008-03-14 02:57:55,0
35916,40.915083,111.711083,2008-03-14 03:06:40,181,2008-03-14 03:43:02,7

In [48]:
diary2 = mdg.generate(30*24, start_time)
print(diary2)

              datetime  abstract_location
0  2022-04-20 08:00:00                  0
1  2022-04-21 10:00:00                  1
2  2022-04-22 09:00:00                  0
3  2022-04-23 13:00:00                  1
4  2022-04-23 18:00:00                  2
5  2022-04-23 19:00:00                  0
6  2022-04-24 01:00:00                  1
7  2022-04-24 10:00:00                  2
8  2022-04-24 18:00:00                  3
9  2022-04-24 19:00:00                  4
10 2022-04-24 22:00:00                  5
11 2022-04-25 15:00:00                  6
12 2022-04-25 19:00:00                  0
13 2022-04-27 10:00:00                  1
14 2022-04-27 19:00:00                  2
15 2022-04-28 19:00:00                  3
16 2022-04-29 10:00:00                  4
17 2022-04-29 19:00:00                  5
18 2022-04-29 20:00:00                  6
19 2022-04-29 22:00:00                  0
20 2022-05-04 08:00:00                  1
21 2022-05-04 11:00:00                  2
22 2022-05-04 12:00:00                  3
23 2022-05-04 14:00:00                  4
24 2022-05-04 15:00:00                  5
25 2022-05-04 16:00:00                  6
26 2022-05-05 02:00:00                  7
27 2022-05-05 03:00:00                  8
28 2022-05-05 06:00:00                  0
29 2022-05-09 19:00:00                  1
30 2022-05-09 20:00:00                  0
31 2022-05-10 19:00:00                  1
32 2022-05-10 22:00:00                  2
33 2022-05-10 23:00:00                  3
34 2022-05-11 10:00:00                  4
35 2022-05-11 12:00:00                  5
36 2022-05-11 13:00:00                  6
37 2022-05-11 14:00:00                  0
38 2022-05-12 16:00:00                  1
39 2022-05-13 02:00:00                  2
40 2022-05-13 05:00:00                  3
41 2022-05-13 09:00:00                  4
42 2022-05-13 20:00:00                  0
43 2022-05-16 12:00:00                  1
44 2022-05-16 22:00:00                  2
45 2022-05-17 09:00:00                  0

In [49]:
stdf

             lat         lng            datetime  uid    leaving_datetime
0      39.983806  116.299436 2008-10-23 03:01:40  000 2008-10-23 04:08:07
1      39.999666  116.324510 2008-10-23 04:32:52  000 2008-10-23 09:42:25
2      40.008994  116.321445 2008-10-23 09:44:50  000 2008-10-23 10:09:16
3      40.007759  116.319107 2008-10-23 10:09:16  000 2008-10-23 10:31:25
4      40.008842  116.321856 2008-10-23 10:31:25  000 2008-10-26 13:44:07
...          ...         ...                 ...  ...                 ...
35912  39.977017  116.310683 2008-02-17 01:25:55  181 2008-02-17 04:17:57
35913  39.983617  116.307908 2008-02-17 04:27:53  181 2008-02-17 05:21:46
35914  39.983600  116.300225 2008-02-17 05:25:01  181 2008-02-17 10:39:57
35915  39.989217  116.298675 2008-02-17 10:42:11  181 2008-03-14 02:57:55
35916  40.915083  111.711083 2008-03-14 03:06:40  181 2008-03-14 03:43:02

[35917 rows x 5 columns]

In [54]:
stdf.groupby(["lat","lng"])